# Generated by Django 3.2 on 2022-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('redirect_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
